### ISSUE TITLE
app-editors/vscode-1.44.2 version bump request

### ISSUE THREAD

**Issue by mercuriete** [elprans/atom-overlay#50] opened 2020-03-27 16:23 UTC
there are a new version of vscode 1.43.2

I did a [simple version bump](https://wiki.gentoo.org/wiki/Custom_repository#Simple_version_bump_of_an_ebuild_in_the_local_repository) and it woks for me. (edited: obsolete comment)

I can try to do a pull request if you want.

Thanks in advance.

EDITED:

now there are another version 1.44.2
as pointed by @Tatsh
with new requirements.

**Comment by elprans** [comment] 2020-03-27 16:31
That version requires a dev-util/electron bump as well, and that ain't as simple, unfortunately.

**Comment by mercuriete** [comment] 2020-03-27 16:32
ok thanks

**Comment by 12101111** [comment] 2020-04-05 02:23
I have build electron-7
![图片](https://user-images.githubusercontent.com/8438475/78465295-6b3f6200-7726-11ea-8510-67f0a381f63e.png)
However, a simple recompilation of the native module does not work on vscode 1.43.
(The version of electron is 7.2.1, but I also try version 7.1.4 that visual studio code currently use)
![图片](https://user-images.githubusercontent.com/8438475/78465264-fd933600-7725-11ea-8311-80108ca9531a.png)
At least `vscode-sqlite3` and `oniguruma` is broken.

**Comment by Tatsh** [comment] 2020-04-30 09:59
Now 1.44.2, which uses Electron 7.1.11

**Comment by 12101111** [comment] 2020-04-30 10:32
[my overlay](https://github.com/12101111/overlay) has ebuild for electron 7/8 (and electron-9 on my local disk).

Also I write a ebuild to compile vscode using official way (`yarn gulp vscode-linux-x64-min`).

I don't known why this happened, but using local electron installation to compile native modules will lead to error like above(`vscode-sqlite3` is broken, and errors like "An unknown error occurred")

The relevant code of my ebuild is at https://github.com/12101111/overlay/blob/master/app-editors/vscode/vscode-1.44.2.ebuild#L109

The commented out part(`if use system-electron`) will cause this error and the `else` part can work normally(Even my system is using musl libc and the binary Electron is using glibc)

**Comment by mercuriete** [comment] 2020-04-30 10:54
I will change the title of this issue
from
app-editors/vscode-1.43.2 version bump request
to
app-editors/vscode-1.44.2 version bump request

sorry for the inconveniences.

**Comment by Tatsh** [comment] 2020-05-01 01:12
> [my overlay](https://github.com/12101111/overlay) has ebuild for electron 7/8 (and electron-9 on my local disk).
> 
> Also I write a ebuild to compile vscode using official way (`yarn gulp vscode-linux-x64-min`).
> 
> I don't known why this happened, but using local electron installation to compile native modules will lead to error like above(`vscode-sqlite3` is broken, and errors like "An unknown error occurred")
> 
> The relevant code of my ebuild is at https://github.com/12101111/overlay/blob/master/app-editors/vscode/vscode-1.44.2.ebuild#L109
> 
> The commented out part(`if use system-electron`) will cause this error and the `else` part can work normally(Even my system is using musl libc and the binary Electron is using glibc)

There's a downside to this build. Various features get hidden behind flags, like the ability to use the Remote extensions.

**Comment by 12101111** [comment] 2020-05-01 03:12
Most functions of vscode is custom by `product.json`, which can be apply by `savedconfig` USE.

See also: https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

However, using product.json from Microsoft's visual studio code directly has a [license](https://code.visualstudio.com/license) problem:

> You may not
>    reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software except and solely to the extent required by third party licensing terms governing use of certain open source components that may be included in the software;

See also: https://github.com/Microsoft/vscode/issues/60#issuecomment-255562539

So people can edit `product.json` or copy `product.json` from somewhere and save as `/etc/portage/savedconfig/app-editors/vscode-1.44.2` to use it, but I don’t make a judgment about whether this behavior is legal

And there is an [Open VSX Registry](https://open-vsx.org/) which is a replacement of microsoft's extensions gallery

https://github.com/microsoft/vscode/issues/31168

**Comment by Tatsh** [comment] 2020-05-01 07:35
That seems like the most reasonable option and I see you've already implemented it. Other than that, I'd like to see about getting `system-electron` USE working.

Maybe we can have a USE flag like `electron-bin` to switch to a `-bin` Electron ebuild? For those in a hurry and don't care so much about purity.

**Comment by 12101111** [comment] 2020-05-01 14:07
`system-electron` should work now: https://github.com/12101111/overlay/commit/b5f9677c08b1d57bf0b21f31b1c20beea4e24d97

**Comment by Tatsh** [comment] 2020-05-01 22:05
I get strange slot output from eix from your Electron ebuild(s):

```
[U] dev-util/electron
     Available versions:
     (1.6)  (~)1.6.18^d[1]
     (1.7)  (~)1.7.16^d[1]
     (2.0)  (~)2.0.17-r2^d[1]
     (3.1)  (~)3.1.8^d[1]
     (6.1)  (~)6.1.6-r1^d[1]
     (${PV%%[.+]*}) (~)7.2.4^d[2] (~)8.2.5^d[2]
```

**Comment by Tatsh** [comment] 2020-05-01 22:09
Also you need to update the Manifest because it mentions your electron-9 ebuild that doesn't exist in your repo yet.

**Comment by Tatsh** [comment] 2020-05-02 04:21
I got extremely close with the v8 snapshot build but it failed (`dev-util/electron-7.2.4`):

```
In file included from ../../third_party/blink/renderer/platform/exported/web_rtc_rtp_source.cc:5:
../../third_party/blink/public/platform/web_rtc_rtp_source.h:40:28: error: no template named 'unique_ptr' in namespa
ce 'std'
BLINK_PLATFORM_EXPORT std::unique_ptr<WebRTCRtpSource> CreateRTCRtpSource(
                      ~~~~~^
5 warnings and 1 error generated.
```

**Comment by Tatsh** [comment] 2020-05-02 07:11
> I get strange slot output from eix from your Electron ebuild(s):
> 
> ```
> [U] dev-util/electron
>      Available versions:
>      (1.6)  (~)1.6.18^d[1]
>      (1.7)  (~)1.7.16^d[1]
>      (2.0)  (~)2.0.17-r2^d[1]
>      (3.1)  (~)3.1.8^d[1]
>      (6.1)  (~)6.1.6-r1^d[1]
>      (${PV%%[.+]*}) (~)7.2.4^d[2] (~)8.2.5^d[2]
> ```

@12101111 I'm pretty sure `SLOT` is read directly from the ebuild by eix, so expanding `$PV` is not a good idea. This probably wouldn't be accepted by Gentoo upstream.

**Comment by 12101111** [comment] 2020-05-02 12:32
> I got extremely close with the v8 snapshot build but it failed (`dev-util/electron-7.2.4`):
> 
> ```
> In file included from ../../third_party/blink/renderer/platform/exported/web_rtc_rtp_source.cc:5:
> ../../third_party/blink/public/platform/web_rtc_rtp_source.h:40:28: error: no template named 'unique_ptr' in namespa
> ce 'std'
> BLINK_PLATFORM_EXPORT std::unique_ptr<WebRTCRtpSource> CreateRTCRtpSource(
>                       ~~~~~^
> 5 warnings and 1 error generated.
> ```

This is fixed now.



> > I get strange slot output from eix from your Electron ebuild(s):
> > ```
> > [U] dev-util/electron
> >      Available versions:
> >      (1.6)  (~)1.6.18^d[1]
> >      (1.7)  (~)1.7.16^d[1]
> >      (2.0)  (~)2.0.17-r2^d[1]
> >      (3.1)  (~)3.1.8^d[1]
> >      (6.1)  (~)6.1.6-r1^d[1]
> >      (${PV%%[.+]*}) (~)7.2.4^d[2] (~)8.2.5^d[2]
> > ```
> 
> @12101111 I'm pretty sure `SLOT` is read directly from the ebuild by eix, so expanding `$PV` is not a good idea. This probably wouldn't be accepted by Gentoo upstream.

`${PV%%[.+]*}` is copy from ebuild of openjdk and don't have issue on my system(with eix 0.33.11). Anyway I have changed  `SLOT` into pure number.

**Comment by Tatsh** [comment] 2020-05-02 17:51
Got to here:

```
[18222/19030]
FAILED: obj/third_party/blink/renderer/platform/platform/canvas_color_params.o
../../third_party/blink/renderer/platform/graphics/canvas_color_params.cc:93:26: error: no member named 'CommandLine
' in namespace 'base'
  auto* cmd_line = base::CommandLine::ForCurrentProcess();
                   ~~~~~~^
../../third_party/blink/renderer/platform/graphics/canvas_color_params.cc:111:26: error: no member named 'CommandLin
e' in namespace 'base'
  auto* cmd_line = base::CommandLine::ForCurrentProcess();
                   ~~~~~~^
2 errors generated.
```

**Comment by 12101111** [comment] 2020-05-03 01:49
> Got to here:
> 
> ```
> [18222/19030]
> FAILED: obj/third_party/blink/renderer/platform/platform/canvas_color_params.o
> ../../third_party/blink/renderer/platform/graphics/canvas_color_params.cc:93:26: error: no member named 'CommandLine
> ' in namespace 'base'
>   auto* cmd_line = base::CommandLine::ForCurrentProcess();
>                    ~~~~~~^
> ../../third_party/blink/renderer/platform/graphics/canvas_color_params.cc:111:26: error: no member named 'CommandLin
> e' in namespace 'base'
>   auto* cmd_line = base::CommandLine::ForCurrentProcess();
>                    ~~~~~~^
> 2 errors generated.
> ```

fixed: https://github.com/12101111/overlay/commit/31c29affac63a1c084b14ccb7db689892a347376

**Comment by Tatsh** [comment] 2020-05-03 08:18
Got to here (`ninja -v ... -C out/Release electron chromedriver`):

```
[6893/11388]
FAILED: obj/components/viz/service/service/software_output_device_proxy.o
In file included from ../../components/viz/service/display_embedder/software_output_device_proxy.cc:5:
../../components/viz/service/display_embedder/software_output_device_proxy.h:46:3: error: unknown type name 'THREAD_CHECKER'
  THREAD_CHECKER(thread_checker_);
```

**Comment by 12101111** [comment] 2020-05-03 08:41
> Got to here (`ninja -v ... -C out/Release electron chromedriver`):
> 
> ```
> [6893/11388]
> FAILED: obj/components/viz/service/service/software_output_device_proxy.o
> In file included from ../../components/viz/service/display_embedder/software_output_device_proxy.cc:5:
> ../../components/viz/service/display_embedder/software_output_device_proxy.h:46:3: error: unknown type name 'THREAD_CHECKER'
>   THREAD_CHECKER(thread_checker_);
> ```

fixed: https://github.com/12101111/overlay/commit/6f2369e776f978172100407539fabd0aa5c655c4

**Comment by Tatsh** [comment] 2020-05-03 11:35
Got to here:

```
[8728/11388] 
FAILED: obj/chrome/browser/ui/libgtkui/libgtkui/select_file_dialog_impl_kde.o
In file included from ../../chrome/browser/ui/libgtkui/select_file_dialog_impl_kde.cc:27:                                                                                           
In file included from ../../chrome/browser/ui/libgtkui/select_file_dialog_impl.h:18:                                                                                                
In file included from ../../ui/aura/window.h:35:                                                                                                                                    
In file included from ../../ui/compositor/layer_owner.h:14:                                                                                                                         
In file included from ../../ui/compositor/layer.h:28:                                                                                                                               
In file included from ../../ui/compositor/compositor.h:26:                                                                                                                          
In file included from ../../components/viz/host/host_display_client.h:16:                                                                                                           
In file included from gen/services/viz/privileged/mojom/compositing/display_private.mojom.h:30:
In file included from gen/services/viz/privileged/mojom/compositing/display_private.mojom-shared.h:27:
gen/gpu/ipc/common/context_result.mojom-shared.h:56:3: error: expected identifier
  Success,
  ^
/usr/include/X11/X.h:350:21: note: expanded from macro 'Success'
#define Success            0    /* everything's okay */
                           ^
1 error generated.
```

**Comment by 12101111** [comment] 2020-05-04 05:23
> Got to here:
> 
> ```
> [8728/11388] 
> FAILED: obj/chrome/browser/ui/libgtkui/libgtkui/select_file_dialog_impl_kde.o
> In file included from ../../chrome/browser/ui/libgtkui/select_file_dialog_impl_kde.cc:27:                                                                                           
> In file included from ../../chrome/browser/ui/libgtkui/select_file_dialog_impl.h:18:                                                                                                
> In file included from ../../ui/aura/window.h:35:                                                                                                                                    
> In file included from ../../ui/compositor/layer_owner.h:14:                                                                                                                         
> In file included from ../../ui/compositor/layer.h:28:                                                                                                                               
> In file included from ../../ui/compositor/compositor.h:26:                                                                                                                          
> In file included from ../../components/viz/host/host_display_client.h:16:                                                                                                           
> In file included from gen/services/viz/privileged/mojom/compositing/display_private.mojom.h:30:
> In file included from gen/services/viz/privileged/mojom/compositing/display_private.mojom-shared.h:27:
> gen/gpu/ipc/common/context_result.mojom-shared.h:56:3: error: expected identifier
>   Success,
>   ^
> /usr/include/X11/X.h:350:21: note: expanded from macro 'Success'
> #define Success            0    /* everything's okay */
>                            ^
> 1 error generated.
> ```

fixed in https://github.com/12101111/overlay/commit/e710f2639574f414ad912d8ce99727549ed17ab0

**Comment by Tatsh** [comment] 2020-05-04 18:54
It built and installed VS Code, but it doesn't work correctly, mostly in loading an Extension page. It either shows up gray or doesn't load. It seems to be crashing according to the log (truncated):

```
#                                                                                                                                                                                   # Fatal error in , line 0                                                                                                                                                           # Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
#                                                                                                                                                                                   #
#                                                                                                                                                                                   #FailureMessage Object: 0x7fff0931ab60                                                                                                                                              #0 0x561f5b7ca999
<unknown>
#1 0x561f5b71ae03
<unknown>
#2 0x561f5d05e76b
<unknown>
#3 0x561f5d0419b2
<unknown>

#
4

0x
561f59acf9e0

v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks<>()

#
5

0x
561f59ace152

v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks()
0x561f5893406a _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 000000000014993b r11: 0000000000000000
 r12: 00007fff0931ae70 r13: 0000003000000008 r14: 00007fff0931ae20 r15: 00007f4089b91780
  di: 00007f4089b927d0  si: 0000000000000000  bp: 00007fff0931ab50  bx: 0000561f5f9b1eb5
  dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000001  sp: 00007fff0931ab50
  ip: 0000561f5d047022 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[3769539:0504/145047.043607:INFO:CONSOLE(4811)] "embedded page crashed", source: file:///usr/lib64/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (4811)
```

I used the Settings Sync extension and I can't load its main configuration page with this build, which means it cannot work.

Do you think it would work if Electron 7.1.11 were used?

**Comment by Tatsh** [comment] 2020-05-04 18:58
Electron itself crashes its browser when I click on *API Demos*. The window turns white.

Log:

<details>

```
$ /usr/lib64/electron-7/electron
Electron 7.2.4 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
Opening in existing browser session.
[3771530:3771530:0100/000000.698595:ERROR:broker_posix.cc(43)] Invalid node channel message
Opening in existing browser session.
[3771811:3771811:0100/000000.515029:ERROR:broker_posix.cc(43)] Invalid node channel message


#
# Fatal error in , line 0
# Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
#
#
#
#FailureMessage Object: 0x7ffe6f019ce0#0 0x559c2ef75999 <unknown>
#1 0x559c2eec5e03 <unknown>
#2 0x559c3080976b <unknown>
#3 0x559c307ec9b2 <unknown>
#4 0x559c2d27a9e0 v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks<>()
#5 0x559c2d279152 v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks()
#6 0x559c2d2b1fd7 <unknown>
#7 0x559c2d2aff8b v8::internal::Heap::CollectGarbage()
#8 0x559c2d2b7375 <unknown>
#9 0x559c2d2c6a3a <unknown>
#10 0x559c2ef28222 <unknown>
#11 0x559c2ef39e6c <unknown>
#12 0x559c2ef39b88 <unknown>
#13 0x559c2eee147a <unknown>
#14 0x559c2ef3a788 <unknown>
#15 0x559c2ef06f17 <unknown>
#16 0x559c317565eb <unknown>
#17 0x559c2de32d7b <unknown>
#18 0x559c2de33ac0 <unknown>
#19 0x559c30422757 <unknown>
#20 0x559c2ce61301 <unknown>
#21 0x559c2c0df27d <unknown>
#22 0x7f8762cc2d0b __libc_start_main
#23 0x559c2c0df06a _start
Received signal 4 ILL_ILLOPN 559c307f2022
#0 0x559c2ef75999 <unknown>
#1 0x559c2eec5e03 <unknown>
#2 0x559c2ef75582 <unknown>
#3 0x7f8766a8ef20 <unknown>
#4 0x559c307f2022 <unknown>
#5 0x559c307ec9bf <unknown>
#6 0x559c2d27a9e0 v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks<>()
#7 0x559c2d279152 v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks()
#8 0x559c2d2b1fd7 <unknown>
#9 0x559c2d2aff8b v8::internal::Heap::CollectGarbage()
#10 0x559c2d2b7375 <unknown>
#11 0x559c2d2c6a3a <unknown>
#12 0x559c2ef28222 <unknown>
#13 0x559c2ef39e6c <unknown>
#14 0x559c2ef39b88 <unknown>
#15 0x559c2eee147a <unknown>
#16 0x559c2ef3a788 <unknown>
#17 0x559c2ef06f17 <unknown>
#18 0x559c317565eb <unknown>
#19 0x559c2de32d7b <unknown>
#20 0x559c2de33ac0 <unknown>
#21 0x559c30422757 <unknown>
#22 0x559c2ce61301 <unknown>
#23 0x559c2c0df27d <unknown>
#24 0x7f8762cc2d0b __libc_start_main
#25 0x559c2c0df06a _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 000000000014993b r11: 0000000000000000
 r12: 00007ffe6f019ff0 r13: 0000003000000008 r14: 00007ffe6f019fa0 r15: 00007f8762e53780
  di: 00007f8762e547d0  si: 0000000000000000  bp: 00007ffe6f019cd0  bx: 0000559c3315ceb5
  dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000001  sp: 00007ffe6f019cd0
  ip: 0000559c307f2022 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

</details>

**Comment by Tatsh** [comment] 2020-05-04 19:04
Also your ebuild does not install the .desktop files and the icon for those.

**Comment by mercuriete** [comment] 2020-05-10 01:39
one question:
I had to add the following in my package.use
because of this news:
https://www.gentoo.org/support/news-items/2020-04-22-python3-7.html

```
*/* PYTHON_TARGETS: python3_6 python3_7
*/* PYTHON_SINGLE_TARGET: -* python3_6
app-editors/vscode PYTHON_SINGLE_TARGET: python2_7
net-wireless/gnuradio PYTHON_SINGLE_TARGET: python2_7
```

There are any way to use python 3 in vscode?

**Comment by Tatsh** [comment] 2020-05-10 01:41
Nope. Not until Chromium switches to Python 3 for their build scripts.

**Comment by mercuriete** [comment] 2020-05-10 01:42
thanks for the response.
I am probably installing flatpak in the near future.
Thanks for your work :+1:

**Comment by 12101111** [comment] 2020-05-10 03:25
> It built and installed VS Code, but it doesn't work correctly, mostly in loading an Extension page. It either shows up gray or doesn't load. It seems to be crashing according to the log (truncated):
> 
> ```
> #                                                                                                                                                                                   # Fatal error in , line 0                                                                                                                                                           # Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
> #                                                                                                                                                                                   #
> #                                                                                                                                                                                   #FailureMessage Object: 0x7fff0931ab60                                                                                                                                              #0 0x561f5b7ca999
> <unknown>
> #1 0x561f5b71ae03
> <unknown>
> #2 0x561f5d05e76b
> <unknown>
> #3 0x561f5d0419b2
> <unknown>
> 
> #
> 4
> 
> 0x
> 561f59acf9e0
> 
> v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks<>()
> 
> #
> 5
> 
> 0x
> 561f59ace152
> 
> v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks()
> 0x561f5893406a _start
>   r8: 0000000000000000  r9: 0000000000000000 r10: 000000000014993b r11: 0000000000000000
>  r12: 00007fff0931ae70 r13: 0000003000000008 r14: 00007fff0931ae20 r15: 00007f4089b91780
>   di: 00007f4089b927d0  si: 0000000000000000  bp: 00007fff0931ab50  bx: 0000561f5f9b1eb5
>   dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000001  sp: 00007fff0931ab50
>   ip: 0000561f5d047022 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [3769539:0504/145047.043607:INFO:CONSOLE(4811)] "embedded page crashed", source: file:///usr/lib64/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (4811)
> ```
> 
> I used the Settings Sync extension and I can't load its main configuration page with this build, which means it cannot work.
> 
> Do you think it would work if Electron 7.1.11 were used?

This problem was caused by a wrong patch, but I did not find a solution.

https://github.com/12101111/overlay/issues/1

Without the patch, the code here will cause gcc compilation errors (but no problem with clang): specialization of template after instantiation , and this code was deleted in chromium79 (electron 7 use chromium 78)

**Comment by Tatsh** [comment] 2020-05-10 04:31
Okay I can rebuild without that patch if you push it, but also might as well update to Code 1.45.0?

**Comment by 12101111** [comment] 2020-05-10 05:34
> one question:
> I had to add the following in my package.use
> because of this news:
> https://www.gentoo.org/support/news-items/2020-04-22-python3-7.html
> 
> ```
> */* PYTHON_TARGETS: python3_6 python3_7
> */* PYTHON_SINGLE_TARGET: -* python3_6
> app-editors/vscode PYTHON_SINGLE_TARGET: python2_7
> net-wireless/gnuradio PYTHON_SINGLE_TARGET: python2_7
> ```
> 
> There are any way to use python 3 in vscode?

vscode don't depend on python directly, it use node-gyp which use python.
I will update ebuild for vscode 1.45 and you can use python3 if you use nodejs-12 or above.
However, there are some problems with this ebuild: i18n of vscode and inspector don't work.
I need to do more testing for this.

**Comment by 12101111** [comment] 2020-05-11 15:22
vscode 1.45 is working!
![图片](https://user-images.githubusercontent.com/8438475/81577909-ac3d2d00-93dc-11ea-8e4a-d943848f544f.png)

**Comment by Tatsh** [comment] 2020-05-11 15:47
Did you build Electron without the template-related GCC patch?

What were your USE flags for Electron? I have `USE="X clang cups proprietary-codecs suid system-ffmpeg system-icu tcmalloc -atk -component-build -custom-cflags -kerberos -lto -ozone -pic -pipewire -pulseaudio (-selinux) -system-libvpx -wayland"` (output from `emerge -pv electron`).

**Comment by 12101111** [comment] 2020-05-12 02:28
> Did you build Electron without the template-related GCC patch?
> 
> What were your USE flags for Electron? I have `USE="X clang cups proprietary-codecs suid system-ffmpeg system-icu tcmalloc -atk -component-build -custom-cflags -kerberos -lto -ozone -pic -pipewire -pulseaudio (-selinux) -system-libvpx -wayland"` (output from `emerge -pv electron`).

Patch is updated.

I tested 4 combinations of USE flags： https://github.com/12101111/overlay/issues/1#issuecomment-626472098

**Comment by Tatsh** [comment] 2020-05-12 18:23
Okay. Maybe I will try building tonight but I sort of want to wait till you get Developer Tools within Electron to work. It's useful for bug reports.

**Comment by 12101111** [comment] 2020-05-16 07:46
![图片](https://user-images.githubusercontent.com/8438475/82113958-4fe75e00-978c-11ea-96ad-e7a323d3ef3f.png)

Developer Tools works.

**Comment by Tatsh** [comment] 2020-05-16 23:24
Electron didn't build for me. `/var/tmp/portage/dev-util/electron-7.3.0/temp/build.log`

```
FAILED: obj/base/base/trace_event_memory_overhead.o
clang++ -MMD -MF obj/base/base/trace_event_memory_overhead.o.d -DUSE_SYMBOLIZE -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFIL
E_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -DGLIB_VERSI
ON_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -I../.. -Igen -I../../third_party/boringssl/src/include -fno-strict-aliasing --param=ssp-buffer-size=
4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -no-canonical-pre
fixes -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefin
ed-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-xor-used-as-pow -Wno-c99-designator -Wno-reorder-init-list -Wno-final-dtor-non-final-class -fno
-omit-frame-pointer -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wglobal-constructors -Wexit-time-destructors -Wshadow -I/usr/lib64/libf
fi/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wexit-time-destructors -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -O2 -pipe -march=native -c
 ../../base/trace_event/trace_event_memory_overhead.cc -o obj/base/base/trace_event_memory_overhead.o
In file included from ../../base/trace_event/trace_event_memory_overhead.cc:5:
../../base/trace_event/trace_event_memory_overhead.h:60:29: error: no type named 'string' in namespace 'std'
  void AddString(const std::string& str);
                       ~~~~~^
../../base/trace_event/trace_event_memory_overhead.cc:87:32: error: out-of-line definition of 'AddString' does not match any declaration in 'base::trace_event::TraceEventMemoryOver
head'
void TraceEventMemoryOverhead::AddString(const std::string& str) {
                               ^~~~~~~~~
2 errors generated.
```

**Comment by PF4Public** [comment] 2020-05-24 16:40
@elprans Do you have any plans on updating electron and vscode? Should we wait? :)

**Comment by PF4Public** [comment] 2020-07-16 01:40
I have attempted to write my version of [electron](https://github.com/PF4Public/gentoo-overlay/tree/master/dev-util/electron) and [vscode](https://github.com/PF4Public/gentoo-overlay/tree/master/app-editors/vscode) ebuilds based on the work of @elprans and @12101111.

Anyone interested may find them in my overlay [::pf4public](https://github.com/PF4Public/gentoo-overlay).

They both at the moment miss keywords  as they require some more work, but I could successfully compile them:
![Bildschirmfoto vom 2020-07-16 02-14-23](https://user-images.githubusercontent.com/10319700/87616595-0f6d7780-c71e-11ea-90b3-bb88b15313ea.png)

**Comment by mercuriete** [comment] 2020-07-16 10:42
I gave up with this overlay.
Thanks for your amazing work.

But for people reaching this bug from internet,
You can also try the binary version from dotnet overlay.
If you don't mind having binary blobs on your computer this is a nice replacement.

https://github.com/gentoo/dotnet/blob/master/app-editors/visual-studio-code/visual-studio-code-1.47.1.ebuild

**Comment by elprans** [comment] 2020-09-13 23:26
1.49.0 is in the tree.

**Closed as completed by elprans** 2020-09-13 23:26 UTC
